### ISSUE TITLE
Adding a dataset to the same zenodo sandbox draft as the cache

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#100]
Is there a way to add a static dataset to the same zenodo sandbox draft as the cache? That way it will also be temporary for now, and when I am finished with the paper, I can publish it alongside the intermediate/dynamic datasets in the same release.

**Comment by rodluger** [comment]
Ha, I *think* so? Never thought of testing that. There's no reason I can think of that it would cause issues to have extra files in the draft -- showyourwork shouldn't mess with them, I don't think. The only thing to be aware of is that the DOI for Zenodo/Zenodo Sandbox deposits used for caching is the *concept* doi, while the DOI for static datasets should be the specific *version* doi (see [here](https://help.zenodo.org/#versioning)). Can you give it a try and let me know if it works?

**Comment by jfcrenshaw** [comment]
Sure! I will test this soon.

**Comment by rodluger** [comment]
I tested this [here](https://sandbox.zenodo.org/record/1068003#.YpfPORNKjzc) and it works just fine (see the config file [here](https://github.com/rodluger/pzflow-paper/blob/96b7fd7a575b6fdd04a3d84629114227eacbffba/showyourwork.yml#L20)). The only caveat is that the static dataset must be in a _published_ Zenodo doi (it needs to be public), you can either do a `showyourwork cache freeze` (or `publish`) or manually publish the deposit on Zenodo.
