### ISSUE TITLE
IncompleteFilesException causing issues

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#103]
If a workflow errors or is interrupted during the generation of a file, often we will get the following message the next time we run ``showyourwork``:

```
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    showyourwork build --cleanup-metadata <filenames>

To re-generate the files rerun showyourwork build with the --rerun-incomplete flag.
Incomplete files:
...
```

This is standard Snakemake behavior. However, running the command shown above doesn't actually seem to fix the issue, and this error will just keep showing up until the user manually deletes the offending file(s) and re-runs the workflow. Let's investigate what's going on.

**Comment by rodluger** [comment]
Potentially related to
https://github.com/snakemake/snakemake/issues/828
https://github.com/snakemake/snakemake/issues/1497

**Comment by rodluger** [comment]
A potential workaround may be to simply delete the `.snakemake/incomplete` directory (instead of running `-cleanup-metadata`), but I haven't tested this.

**Comment by mathren** [comment]
-clanup-metadata does not seem to do much when I encountered this error... my workaround has been to clone anew the repo, which is not ideal

**Comment by rodluger** [comment]
@mathren Can you try deleting the `.snakemake/incomplete` directory the next time you encounter this and let me know if that works?

**Comment by rodluger** [comment]
FWIW deleting `.snakemake/incomplete` works for me. I'm going to add this to the docs and close this issue for now.

**Comment by mathren** [comment]
I confirm, works for me too!

**Comment by jsgounot** [comment]
Hi. I'd like to suggest to change `--cleanup-metadata` to actually resolve this problem. For a standard snakemake user, it is very confusing that the cleanup command does not resolve this. Moreover, one user might want to remove one file and not the others. Removing the whole folder will affect all files the same way. Is there a way to reopen this issue?
