### ISSUE TITLE
Caching and cache-logging not occurring 

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#105]
_Originally posted by @jfcrenshaw in https://github.com/showyourwork/showyourwork/issues/102#issuecomment-1146221679_

On my dept machine, I started with a clean repo and clean install. I copied over the relevant changes from your diff, and upgraded to `v0.3.0.dev8`. Specifically, `showyourwork --version` shows `0.3.0.dev8` and `showyourwork.yml` has `version: 0.3.0.dev8` at the top.

I then created a new Zenodo sandbox cache using `showyourwork cache create`. This was successful, and I confirmed online that the cache exists.

I then ran `showyourwork`, and got the following output:
```
❯ showyourwork
Setting up the workflow...
Creating conda environment environment.yml...
Downloading and installing remote packages.
Environment for environment.yml created (location: .snakemake/conda/8a6b2681ea58482fdf16284367bba157)
Running user rule train_main_galaxy_flow...
Running user rule train_conditional_galaxy_flow...
Generating figure output: src/tex/figures/galaxy_flow_losses.pdf...
Generating figure output: src/tex/figures/conditional_galaxy_corner.pdf...
Running user rule train_two_moons_flow...
Generating figure output: src/tex/figures/twomoons_example.pdf...
Generating figure output: src/tex/figures/main_galaxy_corner.pdf...
Generating the article PDF...
Done!
```

Notice there is no mention of caching. There is also no Zenodo debugging info in the log. My `.showyourwork/logs/showyourwork.log` shows

```
Setting up the workflow...
Creating conda environment environment.yml...
Downloading and installing remote packages.

... skipping all the conda install stuff ...

Environment for environment.yml created (location: .snakemake/conda/8a6b2681ea58482fdf16284367bba157)
Running user rule train_main_galaxy_flow...
Running user rule train_conditional_galaxy_flow...
Generating figure output: src/tex/figures/galaxy_flow_losses.pdf...
Generating figure output: src/tex/figures/conditional_galaxy_corner.pdf...
Running user rule train_two_moons_flow...
Generating figure output: src/tex/figures/twomoons_example.pdf...
Generating figure output: src/tex/figures/main_galaxy_corner.pdf...
Generating the article PDF...
Done!
```

I was worried if somehow the update to `v0.3.0.dev8` didn't propagate. But I checked `.showyourwork/showyourwork.yml` and confirmed it shows `version: 0.3.0.dev8`. I also checked `.showyourwork/config.json` which also shows `"version": "0.3.0.dev8"`.

I then pushed the changes to Github and cloned everything onto my personal laptop. I also copied the exact same `SANDBOX_TOKEN` from my dept machine to my laptop.

I ran `showyourwork`, and got the following output
```
❯ showyourwork
Setting up the workflow...
User authentication for 10.5072/zenodo.1069391 is valid.
Creating conda environment environment.yml...
Downloading and installing remote packages.
Environment for environment.yml created (location: .snakemake/conda/e8f99b34214df6ee91c51c4fae9c4a5a)
Running user rule train_main_galaxy_flow...
Searching remote file cache: src/data/main_galaxy_flow...
Required version of file not found in cache: src/data/main_galaxy_flow.
Running rule from scratch...
Caching output file on remote: src/data/main_galaxy_flow...
############################################################################## 100.0%
Generating figure output: src/tex/figures/main_galaxy_corner.pdf...
Running user rule train_conditional_galaxy_flow...
Searching remote file cache: src/data/conditional_galaxy_flow...
Required version of file not found in cache: src/data/conditional_galaxy_flow.
Running rule from scratch...
Caching output file on remote: src/data/conditional_galaxy_flow...
############################################################################## 100.0%
Generating figure output: src/tex/figures/conditional_galaxy_corner.pdf...
Generating figure output: src/tex/figures/galaxy_flow_losses.pdf...
Running user rule train_two_moons_flow...
Searching remote file cache: src/data/two_moons_flow.pzflow.pkl...
Required version of file not found in cache: src/data/two_moons_flow.pzflow.pkl.
Running rule from scratch...
Caching output file on remote: src/data/two_moons_flow.pzflow.pkl...
############################################################################## 100.0%
Generating figure output: src/tex/figures/twomoons_example.pdf...
Generating the article PDF...
Done!
```

In addition, `.showyourwork/logs/showyourwork.log` shows
```
Setting up the workflow...
Testing if user is authenticated for 10.5072/zenodo.1069391...
User authentication for 10.5072/zenodo.1069391 is valid.
Creating conda environment environment.yml...
Downloading and installing remote packages.

... skipping all the conda install stuff ...

Environment for environment.yml created (location: .snakemake/conda/e8f99b34214df6ee91c51c4fae9c4a5a)
Running user rule train_main_galaxy_flow...
Searching remote file cache: src/data/main_galaxy_flow...
Searching Zenodo cache...
Zenodo DOI not provided in `zenodo.yml`.
Searching Zenodo Sandbox cache...
Attempting to access Zenodo Sandbox deposit with DOI 10.5072/zenodo.1069391...
Searching for file `train_main_galaxy_flow` with hash `7f1ce31b53917ddb563f88eea0987c407979d0da5ac934ae58764e57f47c753d`...
File train_main_galaxy_flow not found in deposit with DOI 10.5072/zenodo.1069391.
Attempting to access Zenodo Sandbox record with DOI 10.5072/zenodo.1069391...
Required version of file not found in cache: src/data/main_galaxy_flow.
Running rule from scratch...
Caching output file on remote: src/data/main_galaxy_flow...
Generating figure output: src/tex/figures/main_galaxy_corner.pdf...
Running user rule train_conditional_galaxy_flow...
Searching remote file cache: src/data/conditional_galaxy_flow...
Searching Zenodo cache...
Zenodo DOI not provided in `zenodo.yml`.
Searching Zenodo Sandbox cache...
Attempting to access Zenodo Sandbox deposit with DOI 10.5072/zenodo.1069391...
Searching for file `train_conditional_galaxy_flow` with hash `461d9ed4208616aa6b4d21aedb8e0222fa6abae5a4d0bf55a3e7e60627637ae0`...
Inspecting candidate file `train_main_galaxy_flow` with hash `461d9ed4208616aa6b4d21aedb8e0222fa6abae5a4d0bf55a3e7e60627637ae0`...
Cache miss for file {entry['filename']}. Skipping...
File train_conditional_galaxy_flow not found in deposit with DOI 10.5072/zenodo.1069391.
Attempting to access Zenodo Sandbox record with DOI 10.5072/zenodo.1069391...
Required version of file not found in cache: src/data/conditional_galaxy_flow.
Running rule from scratch...
Caching output file on remote: src/data/conditional_galaxy_flow...
Generating figure output: src/tex/figures/conditional_galaxy_corner.pdf...
Generating figure output: src/tex/figures/galaxy_flow_losses.pdf...
Running user rule train_two_moons_flow...
Searching remote file cache: src/data/two_moons_flow.pzflow.pkl...
Searching Zenodo cache...
Zenodo DOI not provided in `zenodo.yml`.
Searching Zenodo Sandbox cache...
Attempting to access Zenodo Sandbox deposit with DOI 10.5072/zenodo.1069391...
Searching for file `train_two_moons_flow` with hash `14ff808c26600817362e70af2ffa6c5931e6dc0ef2dbb03d00b774114f26d738`...
Inspecting candidate file `train_conditional_galaxy_flow` with hash `14ff808c26600817362e70af2ffa6c5931e6dc0ef2dbb03d00b774114f26d738`...
Cache miss for file {entry['filename']}. Skipping...
Inspecting candidate file `train_main_galaxy_flow` with hash `14ff808c26600817362e70af2ffa6c5931e6dc0ef2dbb03d00b774114f26d738`...
Cache miss for file {entry['filename']}. Skipping...
File train_two_moons_flow not found in deposit with DOI 10.5072/zenodo.1069391.
Attempting to access Zenodo Sandbox record with DOI 10.5072/zenodo.1069391...
Required version of file not found in cache: src/data/two_moons_flow.pzflow.pkl.
Running rule from scratch...
Caching output file on remote: src/data/two_moons_flow.pzflow.pkl...
Generating figure output: src/tex/figures/twomoons_example.pdf...
Generating the article PDF...
Done!
```

As you can see, when I run the exact same code on my laptop, the caching and new caching debugging dialog works fine. I looked at the cache online and confirmed all the files were there. 

Furthermore, after `showyourwork` on my laptop caches everything on Zenodo, the Github action runs perfectly. So the only problem is with running `showyourwork` on my dept machine. I know this is the hardest thing for you to debug since you don't have access to that machine! (unless you still have UW credentials?)

But somehow, `showyourwork` is interacting with the computing environment in some mysterious way that is changing its behavior on the two machines. It's weird that not only is the caching not occurring on the dept machine, but none of the caching dialog gets printed as well.

I'll keep thinking about this, but just wanted to give you an update, and see if you had any ideas.

Also, if you want, I can close this issue and open a new one for the dept machine caching not working, since the github caching is working fine now.

**Comment by jfcrenshaw** [comment]
_Originally posted by @rodluger in https://github.com/showyourwork/showyourwork/issues/102#issuecomment-1147732007_

> I'll poke around the code a bit to see if I can think of anything. 
> ...
> But right off the bat, this smells like another git version issue. Can you check that you're running git>=2.22.0?

**Comment by jfcrenshaw** [comment]
@rodluger I don't think it's a git version issue?

I am using a conda-installed version of git as a lazy way to get around my lack of sudo privileges. My `environment.yml` contains `git=2.35.3` as a dependency, and I am calling `showyourwork` from a conda environment whose git is the exact same version number. 

As a check, I added 
```python
import subprocess
print(subprocess.check_output(["git", "--version"]))
```
to one of my plotting scripts, and it prints out `git version 2.35.3` as well.

So the two environments that (I think) are relevant:
1. The environment from which I call `showyourwork`
2. The conda environment used by snakemake, defined in `environment.yml`, from which the scripts are run

have git versions >= `2.22.0`

I guess it is possible that the caching functionality is getting called from some third environment that doesn't contain its own git, and so is using the system git, which is only `1.8.3.1`. Hopefully, you know if this is the case?

**Comment by jfcrenshaw** [comment]
Ahh there is a third environment under `~/.showyourwork/`! I activated that environment, and then `git --version` yields `1.8.3.1`. 

After running `conda install git`, I switched back to my original environment. Now calling `showyourwork` shows caching dialog. I.e.
```
Testing if user is authenticated for 10.5072/zenodo.1069391...
User authentication for 10.5072/zenodo.1069391 is valid.
```

I will test if it can update the cache.

**Comment by jfcrenshaw** [comment]
Now `showyourwork` silently fails
```bash
❯ showyourwork
User authentication for 10.5072/zenodo.1069391 is valid.
Running user rule train_two_moons_flow...
Searching remote file cache: src/data/two_moons_flow.pzflow.pkl...

❯ 
```

Looking at the log:
```bash
Testing if user is authenticated for 10.5072/zenodo.1069391...
User authentication for 10.5072/zenodo.1069391 is valid.
Running user rule train_two_moons_flow...
Searching remote file cache: src/data/two_moons_flow.pzflow.pkl...
Searching Zenodo cache...
Zenodo DOI not provided in `zenodo.yml`.
Searching Zenodo Sandbox cache...
Attempting to access Zenodo Sandbox deposit with DOI 10.5072/zenodo.1069391...
Attempting to access Zenodo Sandbox record with DOI 10.5072/zenodo.1069391...
Traceback (most recent call last):
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 142, in fetch
    raise exceptions.FileNotFoundOnZenodo(None)
showyourwork.exceptions.zenodo.FileNotFoundOnZenodo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 599, in _callback
    raise ex
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 581, in cached_or_run
    self.workflow.output_file_cache.fetch(job)
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 152, in fetch
    sandbox.download_file(
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/showyourwork/zenodo.py", line 698, in download_file
    self.download_file_from_record(
  File "/phys/users/jfc20/.showyourwork/env/lib/python3.9/site-packages/showyourwork/zenodo.py", line 493, in download_file_from_record
    logger.debug(
NameError: name 'logger' is not defined
```

It looks like it can't find `two_moons_flow.pzflow.pkl`, even though [that file is present in the cache](https://sandbox.zenodo.org/deposit/1069392).

**Comment by rodluger** [comment]
Good investigative work! Looks like the last error is simply due to the fact that I forgot to define `logger` in that scope. I just fixed that in the latest commit, so the `FileNotFoundOnZenodo ` should be caught in the enclosing scope and it should move on to the next file / deposit as it searches for a match.

Can you set `version: d8a8d7fe32960fe5e67d0c76eb4b27adc88a949b` in your config file and try re-running the workflow? If it works, I'll release a new dev-release on PyPI.

**Comment by rodluger** [comment]
Oh, I forgot to mention that I also [changed the way I query the current git branch](https://github.com/showyourwork/showyourwork/commit/d8a8d7fe32960fe5e67d0c76eb4b27adc88a949b#diff-9797df93533fd13c93ba1fa624146af5096fb0fca07f7573d89bc24bcd8e1bdaR49) to something that should be compatible with older versions of git. So you probably won't need to use the `conda` `git` anymore.

**Comment by jfcrenshaw** [comment]
I added `version: d8a8d7fe32960fe5e67d0c76eb4b27adc88a949b` and everything works!

I also removed the updated git, and re-ran everything with `git version 1.8.3.1` and everything worked again!

So all of these issues are resolved! Thanks so much! 😁🎉

**Comment by rodluger** [comment]
Awesome, thank you!
