### ISSUE TITLE
Failing to build with cache present

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#109]
Loving showyourwork (in particular the newest version is really awesome). 

I have found a strange problem where the builds on Github fail after the first one... I am writing this on an public repo so I guess I can just link the action 

https://github.com/arm61/reporting_sampling/actions

Note that I deleted the action that was successful then the first commit occurred.

**Comment by rodluger** [comment]
Looks like a showyourwork bug. I'll have it fixed later this morning. In the meantime you could bump the cache (set `article-cache-number: 1`) in the GitHub action yaml file (see the docs for details), which should bypass the issue for you.

**Comment by arm61** [comment]
I did try that, but will give it another bash.

**Comment by arm61** [comment]
Actually I think I had it in the wrong place...

**Comment by arm61** [comment]
Cool that has fixed it but revealed some bugs (I haven't done the Zenodo stuff yet!).

**Comment by rodluger** [comment]
OK, I fixed what was causing the original issue (a bug in the way showyourwork was caching stuff on GH Actions). Feel free to open a new issue if you're running into other problems.
