### ISSUE TITLE
dataset icon for figures with  cached non-public data

### ISSUE THREAD

**Issue by mathren** [showyourwork/showyourwork#113]
Hey Rodrigo! Would you be interested in adding a second dataset icon for figures depending on cached data so that:

* complete figure has three bagdes and links: github link, parent static dataset, cached processed dataset (colors determined by current behavior)
* figure with cache not public/needs to be recreated: last icon above another color (signals costly computation needed to reproduce the result)
* figure with no cached data: two icons only

**Comment by rodluger** [comment]
Definitely. Can probably do this early next week.

**Comment by rodluger** [comment]
Hey @mathren I implemented this on the `main` branch. When you get a chance, can you give it a spin? The cache icon is a recycle symbol, which is blue if the cache has been published on Zenodo (`showyourwork cache publish`) and red if it's still on Sandbox.

**Comment by rodluger** [comment]
This seems to be working on https://github.com/katiebreivik/hush
