### ISSUE TITLE
Fix behavior for cached rules that depend on Zenodo datasets

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#124]
This is an issue identified by @katiebreivik. Snakemake evaluates whether or not to restore a rule's output from the cache based on the hash of all the upstream rules. This check, however, happens _after_ the workflow graph (the DAG) has been built. In `showyourwork`, if a given rule depends on files downloaded from a (static) Zenodo deposit, the current behavior means we must always download those files, regardless of whether the rule is actually executed or simply restored from the cache. This is computationally wasteful -- in @katiebreivik's case, there are hundreds of (very large) files that are used _only_ in that rule, so downloading those files---only to then decide they're not needed, as we don't have to run the rule at all---is silly.

**Comment by rodluger** [comment]
I coded up a minimum working example of the problem [here](https://github.com/showyourwork/showyourwork-example/tree/zenodo-hash). 

**showyourwork.yml:**
```yaml
...
datasets:
  10.5281/zenodo.6515864:
    contents:
      images.tar.gz: src/data/zenodo_dataset.dat

dependencies:
  src/scripts/figure.py:
    - src/data/processed_dataset.dat
```

**Snakefile:**
```python
rule C:
    input:
        "src/data/zenodo_dataset.dat"
    output:
        "src/data/processed_dataset.dat"
    cache:
        True
    ...
```

Figure script `figure.py` depends on `processed_dataset.dat`, which is generated from the static Zenodo-hosted `zenodo_dataset.dat` in a cacheable rule. Here's what happens when we run the workflow on GitHub Actions (see [here](https://github.com/showyourwork/showyourwork-example/runs/7326942604?check_suite_focus=true)):

```
  ...
  Downloading src/data/zenodo_dataset.dat from Zenodo...
  Running user rule C...
  Searching remote file cache: src/data/processed_dataset.dat...
  Restoring from Zenodo Sandbox cache: src/data/processed_dataset.dat...
  ...
```

The workflow correctly restores `processed_dataset.dat` from the cache. However, it only does this after downloading `zenodo_dataset.dat` and computing its checksum, at which point it realizes it's the same as the input to the cached version of the rule.

This behavior is undesirable -- in @katiebreivik's case, there are hundreds of very large datasets in the inputs to the Snakemake rule. They must all be downloaded in order to compute their checksums, even though they're coming from a static Zenodo deposit.

I don't know of any obvious fix to this, but I'll keep thinking.

**Comment by rodluger** [comment]
This may be above my paygrade. I'm asking for help here: https://github.com/snakemake/snakemake/issues/1766

**Comment by rodluger** [comment]
Ok, I have a hack. This could be massaged into a PR for Snakemake but our use case is esoteric enough that I'm going to punt on that. To understand the hack, consider this MWE, based on the code I posted in https://github.com/snakemake/snakemake/issues/1766:

<details>
<summary><strong>Snakefile</strong></summary>

```python
rule main:
    input:
        "C.dat"

# include: "patch.smk"

rule C:
    input:
        "B.dat",
        # PATCH_SNAKEMAKE
    output:
        "C.dat"
    run:
        # Double the input
        print("Running rule C.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number * 2))

rule A:
    output:
        "A.dat"
    params:
        number=0.25
    run:
        # Record the number
        print("Running rule A.")
        with open(output[0], "w") as f:
            f.write(str(params.number))

rule B:
    input:
        "A.dat"
    output:
        "B.dat"
    cache:
        True
    run:
        # Take the square root of the input
        print("Running rule B.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number ** 0.5))
```

</details>

There are three rules, `A`, `B`, and `C`. `A` takes some number as input and records it in `A.dat`. `B` reads that number, takes its square root, and records it in `B.dat`. Finally, `C` reads the result, doubles it, and records it in `C.dat`. Rule `B` is cached.

<details>
<summary><strong>Snakefile</strong></summary>
```bash
#!/bin/bash

# 1. Initial run
echo "Initial run"
echo "==========="
rm -rf cache
mkdir cache
rm *.log
rm -f *.dat
rm -f *.chk
SNAKEMAKE_OUTPUT_CACHE=cache snakemake -c1 --cache 2> 1.log
echo "Workflow output: $(head C.dat)"
echo "Expected output: 1.0"

# 2. Cached run
echo ""
echo "Cached run"
echo "=========="
rm -f *.dat
rm -f *.chk
SNAKEMAKE_OUTPUT_CACHE=cache snakemake -c1 --cache 2> 2.log
echo "Workflow output: $(head C.dat)"
echo "Expected output: 1.0"
```

</details>

**Comment by rodluger** [comment]
Ok, I have a hack. This could be massaged into a PR for Snakemake but our use case is esoteric enough that I'm going to punt on that. Note that this is also specifically a fix for Snakemake `v6.15.5`, which is the version we've pinned in `showyourwork`.

To understand the hack, consider this MWE, based on the code I posted in https://github.com/snakemake/snakemake/issues/1766.

The problem
=========

<details>
<summary><strong>Snakefile</strong></summary>

```python
rule main:
    input:
        "C.dat"

# include: "patch.smk"

rule C:
    input:
        "B.dat",
        # PATCH_SNAKEMAKE
    output:
        "C.dat"
    run:
        # Double the input
        print("Running rule C.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number * 2))

rule A:
    output:
        "A.dat"
    params:
        number=0.25
    run:
        # Record the number
        print("Running rule A.")
        with open(output[0], "w") as f:
            f.write(str(params.number))

rule B:
    input:
        "A.dat"
    output:
        "B.dat"
    cache:
        True
    run:
        # Take the square root of the input
        print("Running rule B.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number ** 0.5))
```

</details>

There are three rules, `A`, `B`, and `C`. `A` takes some number as input and records it in `A.dat`. `B` reads that number, takes its square root, and records it in `B.dat`. Finally, `C` reads the result, doubles it, and records it in `C.dat`. Rule `B` is cached.

Let's create a simple bash script to execute the workflow:

<details>
<summary><strong>build.sh</strong></summary>

```bash
#!/bin/bash

# 1. Initial run
echo "Initial run"
echo "==========="
rm -rf cache
mkdir cache
rm *.log
rm -f *.dat
rm -f *.chk
SNAKEMAKE_OUTPUT_CACHE=cache snakemake -c1 --cache 2> 1.log
echo "Workflow output: $(head C.dat)"
echo "Expected output: 1.0"

# 2. Cached run
echo ""
echo "Cached run"
echo "=========="
rm -f *.dat
rm -f *.chk
SNAKEMAKE_OUTPUT_CACHE=cache snakemake -c1 --cache 2> 2.log
echo "Workflow output: $(head C.dat)"
echo "Expected output: 1.0"
```

</details>

In this script, we run the workflow twice so we can see the behavior once the output has been cached. In between the two workflows, I delete all output files (but preserve the cache). Here's the output when we run this script:

<details>
<summary><strong>stdout</strong></summary>

```
Initial run
===========
Running rule A.
Running rule B.
Running rule C.
Workflow output: 1.0
Expected output: 1.0

Cached run
==========
Running rule A.
Running rule C.
Workflow output: 1.0
Expected output: 1.0
```

</details>

The first time around, things run as expected (`A` -> `B` -> `C`, and the expected number is output into `C.dat`). The second time around, the output is again correct, **but rule A was executed unnecessarily**. Why? Because rule `B` was never executed (see the **stdout**) -- its output was (correctly) restored from cache. The output of rule `A` is used _only_ as input to rule `B`, so there's no point in re-running rule `A` if we're just going to ignore its outputs completely.

The solution
=========

Note that in the **Snakefile** there were two lines of code I commented out. Let's restore them:

<details>
<summary><strong>Snakefile</strong></summary>

```python
rule main:
    input:
        "C.dat"

include: "patch.smk"

rule C:
    input:
        "B.dat",
        PATCH_SNAKEMAKE
    output:
        "C.dat"
    run:
        # Double the input
        print("Running rule C.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number * 2))

rule A:
    output:
        "A.dat"
    params:
        number=0.25
    run:
        # Record the number
        print("Running rule A.")
        with open(output[0], "w") as f:
            f.write(str(params.number))

rule B:
    input:
        "A.dat"
    output:
        "B.dat"
    cache:
        True
    run:
        # Take the square root of the input
        print("Running rule B.")
        with open(input[0], "r") as f:
            number = float(f.read())
        with open(output[0], "w") as f:
            f.write(str(number ** 0.5))
```

</details>

Now, we're including a file `patch.smk` in the workflow and adding the input function `PATCH_SNAKEMAKE` (defined in `patch.smk`) to the list of inputs for rule `C`. Here's the patch file:


<details>
<summary><strong>patch.smk</strong></summary>

```python
import inspect
import types
from pathlib import Path


def get_snakemake_variable(name, default=None):
    """
    Traverse the call stack upwards into Snakemake to obtain
    the value of an internal variable. This is super hacky, but
    AFAIK is the only way to programmatically access the DAG.

    """
    levels = inspect.stack()
    for level in levels:
        value = level.frame.f_locals.get(name, None)
        if value is not None:
            return value
    return default


def job_is_cached(job):
    """
    Return True if a job's outputs will be restored from cache.

    """
    cache = snakemake.workflow.workflow.output_file_cache
    try:
        if cache.exists(job):
            return True
        else:
            return False
    except:
        return False


def get_skippable_jobs(dag):
    """
    Search the DAG and return jobs we can safely skip due to
    downstream cache hits.

    """
    # Get all jobs (nodes) with cache hits
    cached_jobs = set([job for job in dag.jobs if job_is_cached(job)])
    
    # Nodes we can skip
    nodes = set(cached_jobs)

    # Loop until there are no changes to the graph
    new_nodes = True
    while new_nodes:

        new_nodes = set()
        for node in nodes:
        
            # Find all parents that are in `nodes`
            parents = set()
            for file in node.input:
                try:
                    parents |= set(dag.file2jobs(file)).difference(nodes)
                except snakemake.exceptions.MissingRuleException:
                    # Not all files have producers
                    pass

            # Find parents whose children are all in `nodes`
            for parent in parents:
                children = set()
                for file in parent.output:
                    children |= set([job for job in dag.jobs if file in job.input])
                if all([child in nodes for child in children]):
                    new_nodes.add(parent)

        # Add the new batch to the list of all skippable nodes
        nodes |= new_nodes

    # Exclude the cached jobs from the list we'll skip
    nodes = nodes.difference(cached_jobs)

    return nodes


def PATCH_SNAKEMAKE(*args):
    # Wait until the DAG has been built
    snakemake.workflow.checkpoints.patch.get()

    # Patch the caching behavior
    if snakemake.workflow.workflow.output_file_cache:
    
        # Hack to access the workflow graph
        dag = get_snakemake_variable("dag")

        # Get list of jobs we can skip
        skippable_jobs = get_skippable_jobs(dag)

        # Patch the Snakemake method that executes jobs
        scheduler = snakemake.workflow.workflow.scheduler
        for executor in scheduler._executor, scheduler._local_executor:
            if executor:

                # Original method
                _cached_or_run = executor.cached_or_run

                # Intercept jobs we don't need to run
                def wrapper(self, job, run_func, *args):
                    if job in skippable_jobs:
                        # Instead of running this job, we create empty temp 
                        # outputs to trick Snakemake & keep going
                        for output in job.output:
                            if not output.exists:
                                output.set_flags({'temp': True})
                                output.touch_or_create()
                        return
                    else:
                        # We need to run this rule
                        _cached_or_run(job, run_func, *args)

                # Patch the method
                executor.cached_or_run = types.MethodType(wrapper, executor)

    # Dummy output
    return []

checkpoint patch:
    output:
        touch("patch.chk")
    priority:
        snakemake.jobs.Job.HIGHEST_PRIORITY
    run:
        print("Removing unnecessary jobs from the DAG.")
```

</details>

Before I explain it, let's check that it fixes the problem outlined above. Here's the output when running **build.sh** on this modified workflow:

<details>
<summary><strong>stdout</strong></summary>

```
Initial run
===========
Removing unnecessary jobs from the DAG.
Running rule A.
Running rule B.
Running rule C.
Workflow output: 1.0
Expected output: 1.0

Cached run
==========
Removing unnecessary jobs from the DAG.
Running rule C.
Workflow output: 1.0
Expected output: 1.0
```

</details>

Note two things: (1) there's an extra step in the workflow -- the DAG optimization step -- and (2) we're no longer running rule `A` the second time around. Hoorah!

How it works
==========

The patch defines a checkpoint `patch` that runs before all the other rules, but after the workflow graph (DAG) has been created. The function `PATCH_SNAKEMAKE`, which is an input to the main rule of the workflow, blocks until the checkpoint has been executed, giving us an opportunity to (hackily) access the DAG. We check all of the jobs for cache hits and identify the ones whose outputs will be restored from the cache. We then identify all upstream jobs for which all downstream paths end up at a cached rule; these are the jobs we can safely skip. We therefore bypass the `cached_or_run` method (which either runs the job or restores the output from cache) for those jobs. To make Snakemake happy, we still need to generate the expected outputs of those jobs, so we just create empty, temporary files that get deleted as soon as the workflow is done.

There are probably pitfalls to this method that I haven't thought of. For one, we're accessing the DAG by inspecting the call stack, which is _super_ hacky. AFAIK Snakemake doesn't expose the dag to the user in any way, so a `showyourwork`-side patch has to do something like this. A PR for Snakemake would therefore be more elegant.

I also made a decision on which jobs to actually skip. I'm being conservative and skipping jobs that _only_ output files that are used as inputs to rules with cache hits. Jobs that output any additional files are _not_ skipped, regardless of whether those files are actually requested by the user. For example, try adding `touch("foo.dat")` to the list of outputs of rule `A` and `"foo.dat"` to the list of inputs to rule `C` and re-running `build.sh`. This time, rule `A` gets executed, since file `foo.dat` needs to be generated so rule `C` can run (this is good). But now remove `"foo.dat"` from the list of inputs to rule `C`. What should happen now? That file isn't an input to a cacheable rule, but it's also not used anywhere else in the workflow. Should we generate it? I don't know! My implementation errs on the side of caution and forces execution of rule `A` in this case. As far as `showyourwork` is concerned, I think this behavior is fine -- our issue is specifically with the outputs of the `showyourwork`-managed rules that download Zenodo datasets, and those rules only have one output each.

I would appreciate feedback from other users on all this (@katiebreivik @dfm @adrn @jfcrenshaw @MilesCranmer @kazewong ?). Apologies for the length, but it's not a trivial problem!

*NOTE*: Edited to incorporate the graph searching algorithm outlined [below](https://github.com/showyourwork/showyourwork/issues/124#issuecomment-1192733466).

**Comment by rodluger** [comment]
I just realized my solution is not complete, since it only removes rules _one level up_ from rules with cache hits. For example,  consider the chain of rules `Z` -> `A` -> `B (cached)` -> `C`. The solution I proposed would effectively remove `A` from the DAG but not `Z`. We'll have to do a little recursion to search up the graph.

**Comment by rodluger** [comment]
Here's a brief explanation of the algorithm for completeness. Consider this DAG as an example:

![PXL_20220722_160759282](https://user-images.githubusercontent.com/9323819/180480038-8f7c3dbb-1c31-4f9f-8388-c7ccb22b0a2e.jpg)

Black circles are rules, red circles are rules with cache hits. Files are edges (output files are outward arrows; input files are inward arrows). The black squares at the bottom are the target rules for the workflow. We want to eliminate all unnecessary rules upstream of cached rules.

Potential algorithm (may not be optimal):

1. Starting from the red nodes, we look at all their parent nodes. For each parent, if all their children are red nodes, we mark them as blue nodes.
2. We do the same for the blue nodes: look at their parents, and if all their children are either red or blue nodes, we mark them as blue nodes.
3. Repeat step 2 until no more changes are made to the graph.
4. At the end, all nodes marked blue correspond to rules we can eliminate from the DAG.

**Comment by rodluger** [comment]
@katiebreivik When you get a chance, can you use `showyourwork` version [a3e47d02277348029c574389d62888bff9f820a4](https://github.com/showyourwork/showyourwork/tree/a3e47d02277348029c574389d62888bff9f820a4) to test your [hush](https://github.com/katiebreivik/hush) workflow?

Set `optimize_caching: true` in `showyourwork.yml` to enable the graph optimization I implemented in #129.

This _should_ prevent `showyourwork` from downloading all the unnecessary Zenodo deposits on GitHub Actions, provided there's a downstream cache hit.

**Comment by katiebreivik** [comment]
yes! Will do later today!

**Comment by rodluger** [comment]
This seems to be working! 

https://github.com/katiebreivik/hush/runs/7585423723?check_suite_focus=true

(The action failed because the runner ran out of disk space at the very end, but the DAG was optimized correctly and it got as far as uploading an artifact with the compiled PDF.)
