### ISSUE TITLE
Issue with github hyperlinks in arXiv version of built PDF

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#125]
I've noticed that the hyperlinks in the  icons of the pdf compiled by arXiv (from the showyourwork-generated tarball) are broken (possibly same/similar bug as the naming of the cache on zenodo).

For example, the github link for fig. 1 in [this paper](https://arxiv.org/pdf/2206.15338.pdf) should be `https://github.com/mathren/CE_accretors/blob/844cf5fc95e4385cb012462aa336826908de5376/src/scripts/HRD.py` (has correctly linked on the version compiled by github actions) and it is instead `https://arxiv.org/pdf/git@github.com:mathren/CE_accretors/blob/975717fece1bbb3bccfbae0d5b57e748743cb9ad/src/scripts/HRD.py`

_Originally posted by @mathren in https://github.com/showyourwork/showyourwork/issues/117#issuecomment-1182944388_

**Comment by rodluger** [comment]
This is really bad -- thanks for catching it! I'll look into it ASAP.

**Comment by rodluger** [comment]
The issue is almost certainly due to the way you're authenticating locally -- I suspect you're using SSH instead of HTTPS? Can you run the following for me in your terminal

```bash
git config --get remote.origin.url
```

and tell me what you get? That's what `showyourwork` currently uses to infer the URL of your repository. For HTTPS authentication, that returns `https://github.com/<user>/<repo>`. But for SSH, I suspect it returns `git@github.com:<user>/<repo>`. Can you confirm that?

If that's the case, LaTeX sees hyperlinks to files that look like `git@github.com:mathren/CE_accretors/blob/.../src/scripts/....py` and assumes they're relative links, so it tacks on the `arxiv` URL at the front.

Note that if you just use the tarball generated by the GitHub Action (which uses HTTPS authentication), I'm pretty sure all the links resolve correctly:
https://github.com/mathren/CE_accretors/blob/main-pdf/arxiv.tar.gz

I recommend that's what users do in any event, since the output on GitHub Actions is the truly "reproducible" one, since it's guaranteed to always run in an isolated environment from scratch.

All that being said, I can definitely issue a patch for SSH authentication! This is definitely a bug in `showyourwork`. Once you confirm my suspicions I'll release a new version.

Thanks again for catching this!

**Comment by mathren** [comment]
Answering quickly from my phone: yes, I am using SSH instead of https. From the cluster there was some issue in using https when I set the repo up. Your suspicion is most likely correct.

**Comment by rodluger** [comment]
Cool! When you get a chance, can you build the PDF locally using version `eb9b8c28b31f959b0d26c75bfe4a382e17419555` and see if the links point to the correct place? (BTW, there's nothing special about the tex file that gets compiled on the arXiv -- you should get the same broken links when running `showyourwork` locally to generate `ms.pdf`).

**Comment by mathren** [comment]
Will do (likely not earlier than tomorrow though). But I can confirm the links are also broken in the locally build pdf!

**Comment by rodluger** [comment]
Ok, thanks!!

**Comment by mathren** [comment]
Sorry for the long delay. Using `version: cadb4086dd2a46cb68e6acffa73c2f7976e6d64d` this seems to be solved. I get the correct github links from a local compilation.

**Comment by rodluger** [comment]
Thanks @mathren !
