### ISSUE TITLE
Cloning a repo before running "showyourwork build" throws an error

### ISSUE THREAD

**Issue by richinex** [showyourwork/showyourwork#127]
I created a repo in Github and cloned the repo to a sub-folder on my laptop. Then I navigated to the parent folder and ran
```
showyourwork setup user/repo
```
and I got "Directory already exists: repo."

Then I navigated to the subfolder which is the repo and ran showyourwork build and got the error:

# No `showyourwork.yml` config file in current working directory. Are you running `showyourwork` from within your article's repository?

Is this behavior expected?

**Comment by rodluger** [comment]
Yeah, `showyourwork setup user/repo` sets up the git repository for you, so there's no need to manually clone it. Do it in the following order and it should work:

- Create an empty repo on GItHub
- Run `showyourwork setup user/repo`
- `cd` into the repo and run `git push -u origin main` to sync with the remote

See [here](https://show-your.work/en/latest/quickstart/) for details.

**Comment by rodluger** [comment]
Thanks for pointing this out, though. I can at the very least provide a more informative error message, if not edit the code to also work the way you expected.

**Comment by richinex** [comment]
Cool and thank you for the great work. It is an incredible package. Will definitely recommend to colleagues at my Uni.

**Comment by rodluger** [comment]
OK, this has been fixed on `main`, to be released in `0.3.1`. Now, if the user clones an empty `git` repo and runs `showyourwork setup`, setup should proceed without errors. But if there are any files or any commit history in the cloned repo, setup will fail so as not to overwrite history.
