### ISSUE TITLE
Bot no longer commenting on PRs

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#128]
The PR bot in [showyourwork/showyourwork-action/process-pull-request](https://github.com/showyourwork/showyourwork-action/blob/main/process-pull-request/action.yml) is no longer working for some reason.

[This PR](https://github.com/showyourwork/test-pull-request/pull/12) from today should have triggered a bot comment. Compare to an [identical PR](https://github.com/showyourwork/test-pull-request/pull/10) from two days ago where the comment appeared successfully.

Here are the corresponding workflow logs: [from today](https://github.com/showyourwork/test-pull-request/runs/7456323740?check_suite_focus=true#step:2:1) and [from two days ago](https://github.com/showyourwork/test-pull-request/runs/7415941762?check_suite_focus=true#step:2:1). Note that we don't get any error messages -- the composite action simply doesn't run and produces no output.

The tests on the `showyourwork` repo are now [failing](https://github.com/showyourwork/showyourwork/actions/runs/2713863244) because of this.

@MilesCranmer any ideas? Absolutely nothing changed in [showyourwork/showyourwork-action](https://github.com/showyourwork/showyourwork-action) (last commit was 9 days ago). Is this a temporary GitHub issue perhaps?

**Comment by rodluger** [comment]
Ok, I created a [new repository](https://github.com/showyourwork/test-pull-requests) for the pull request tests and things are working correctly now:

https://github.com/showyourwork/test-pull-requests/pull/1#issuecomment-1191866187

No idea why this happened! Closing for now, will re-open if the issue pops back up.

**Comment by MilesCranmer** [comment]
I wonder if it’s something to do with GitHub action max allocation? I think normally for a free account one can use 15 concurrent actions at any time - if there are more than 15 running, perhaps the comment bot will be delayed or something?

**Comment by rodluger** [comment]
Hmm. After the tests all finished I (1) re-ran the action, twice, (2) closed and reopened the PR, (3) added a new commit to the PR. All of those triggered the bot action, but the workflow produced no output and did not comment on the PR. So I don't think it was a usage limit issue. The only thing I can think of is that over the past few days I opened and closed 12 identical pull requests and maybe it got flagged internally as a spambot?
