### ISSUE TITLE
Custom tectonic settings

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#132]
How should one pass custom arguments to the tectonic build? I am trying to pass `-Z shell-escape` so that I can use the `minted` package.

Is there a way I can provide a `Tectonic.toml` file to the build? It looks like there is a `shell_scape` option available there: https://tectonic-typesetting.github.io/book/latest/ref/tectonic-toml.html.

**Comment by rodluger** [comment]
Ah, that's not implemented, but would be easy to add. You'd want to do that in this function: https://github.com/showyourwork/showyourwork/blob/afe0936d70cc381cb18fc7e6b58a537d29184556/showyourwork/tex.py#L11

Specifically, I would add more arguments on this line:
https://github.com/showyourwork/showyourwork/blob/afe0936d70cc381cb18fc7e6b58a537d29184556/showyourwork/tex.py#L60

Note that `args` and `force_args` are used internally; we could create a new `user_args` that is read directly from the `config` dictionary (passed into the method).

If you want to give it a shot with a PR, define a default value for the option (call it `tectonic_args` or something) here: https://github.com/showyourwork/showyourwork/blob/afe0936d70cc381cb18fc7e6b58a537d29184556/showyourwork/config.py#L259

and add an entry to the docs here: https://github.com/showyourwork/showyourwork/blob/main/docs/config.rst

I'm happy to do it, but won't have time until next week probably.

As for the `.toml` file, see #115 ; not yet supported, still thinking about how best to do it.

**Comment by rodluger** [comment]
Added the config option `tectonic_args`, which should be a list of command line options passed to `tectonic`. @MilesCranmer can you test & review #138 when you get a chance?
