### ISSUE TITLE
Custom typewriter fonts broken

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#139]
This took a while to boil down to an MWE but it seems like specifically when you use `showyourwork` to build a document, any use of custom typewriter fonts will break. This is true even when `tectonic`, `xelatex`, and `pdflatex` all compile the typewriter font correctly; it seems like `showyourwork` turns off the custom font for some reason.

Example:
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{showyourwork}
% Custom typewriter font:
\usepackage{inconsolata}
\begin{document}
% Text:
This is a \texttt{mono spaced font example}.
\end{document}
```

When compiling this with `showyourwork`, I see the following:

<img width="655" alt="Screen Shot 2022-08-03 at 3 47 47 PM" src="https://user-images.githubusercontent.com/7593028/182696207-8e69b8b7-4da0-4cfb-becf-ef054a98ff88.png">

When compiling this exact same code with `tectonic src/tex/ms.tex`, I see the following:
<img width="626" alt="Screen Shot 2022-08-03 at 3 48 37 PM" src="https://user-images.githubusercontent.com/7593028/182696354-3b812ee6-b8d2-4c2b-b766-8dcc6559995c.png">

And similarly for `xelatex ms.tex` and `pdflatex ms.tex`. 

Any idea what the reason is for this?

I should add that there are no apparent issues in the log, it just says "Generating the article PDF... Done!".

Cheers,
Miles

**Comment by rodluger** [comment]
When you build with `showyourwork`, [this file](https://github.com/showyourwork/showyourwork/blob/main/showyourwork/workflow/resources/styles/build.tex) gets added to the cwd and gets included when you do `\usepackage{showyourwork}`. (When you build with `tectonic`, that file isn't present and doesn't get loaded). 

Have a look inside that file and see if you spot anything that could be causing this issue. If I were to guess, I'd bet it's these lines:

https://github.com/showyourwork/showyourwork/blob/main/showyourwork/workflow/resources/styles/build.tex#L48-L53

Specifically, try adding `\usepackage{fontspec}` and maybe `\defaultfontfeatures{Extension = .otf}` to your MWE and compile with tectonic. Does that let you reproduce the issue?

**Comment by MilesCranmer** [comment]
Indeed adding `\usepackage{fontspec}` makes `tectonic` experience the same issue

**Comment by MilesCranmer** [comment]
Cool! Thanks for the fix. The PR #140 fixes this. I can confirm the issue goes away with it:
<img width="570" alt="Screen Shot 2022-08-03 at 4 24 00 PM" src="https://user-images.githubusercontent.com/7593028/182704698-9d2be928-e189-49da-ba8e-484f3dcee768.png">

**Comment by rodluger** [comment]
Yeah, this is probably fine. I like the idea of defining the show your work logo as actual text, meaning it will scale appropriately to the right font size wherever `\showyourwork` is used in the manuscript. But other than being cool, it's not particularly useful. It also only works with XeTeX, meaning the version on arXiv (which is compiled with pdflatex) doesn't benefit from it anyways.

**Comment by rodluger** [comment]
Thanks for catching this!

**Comment by MilesCranmer** [comment]
Ah, I see. Yeah I'm not sure what the best way to get that working again is. Maybe there's a way to scale an image by the surrounding text's fontsize? (like `\linewidth` but using fontsize instead?).

**Comment by rodluger** [comment]
Nah, no one would really benefit from that. I think this is fine as is!
