### ISSUE TITLE
I use PyScaffold - how would you recommend migrating from another template-style repository?

### ISSUE THREAD

**Issue by sgbaird** [showyourwork/showyourwork#141]
[PyScaffold](https://pyscaffold.org/) (another alternative would be [`cookiecutter-pypackage`](https://github.com/audreyfeldroy/cookiecutter-pypackage)). [This is a demo repo](https://github.com/pyscaffold/pyscaffold-demo) for PyScaffold that shows the default layout, and [this repo's commit](https://github.com/sparks-baird/xtal2png/tree/0a47c2c4b6cdba4e0cb9ca99ccf729274317ae73) shows the layout with a couple of PyScaffold extensions, and [this repo](https://github.com/sparks-baird/xtal2png) for the fleshed out version.

How would you suggest using `showyourwork` in this context? E.g. start with showyourwork (or PyScaffold) and merge the other layout and see what breaks, create two separate repositories (e.g. one for a Python package and one for the showyourwork article, which depends on the former package), decide on one vs. the other.

**Comment by sgbaird** [comment]
Based on the intro, perhaps two separate repositories would make sense whenever I'm developing a Python package meant for more general use.

> Scientific papers should exist as GitHub repositories comprised of LaTeX files, figure scripts, rules to generate and/or access datasets, a platform/environment specification, **and nothing else.** Anyone should be able to re-generate the article PDF from scratch at the click of a button.

**Comment by dfm** [comment]
Yeah - this is the approach I've taken: one repo for the Python project and a separate (showyourwork-based) repo for the paper, including the former as a dependency. It is a little awkward for development cycle if you're developing them in parallel, so perhaps @rodluger has better advice!

**Comment by rodluger** [comment]
Good question! I agree with @dfm that keeping two separate repos is likely the simplest and more elegant approach. Like he said the dev cycle is a little cumbersome because whenever you make a change to your package you need to commit & push to GitHub then change the pinned version in the paper repo's `environment.yml`.

However, I bet you could save some effort by adding your package as an editable dependency in the paper's `environment.yml`, e.g.:

```yaml
pip:
   - -e ./relative/path/to/package
```

The catch is that `showyourwork` no longer knows whether anything has changed in your package since the last build (since you're no longer pinning a specific version or commit SHA). So you'd have to manually add your package's files as dependencies in `showyourwork.yml`, which is a bit of a pain (although you could use an [anchor](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) to define all the relevant files up top and alias it in the dependencies of individual scripts to greatly reduce the size of your yaml file).

You'd also have to edit the `.github/workflows/build.yml` workflow and manually checkout & install your package in the same relative path so things will work on GitHub actions.

@dfm perhaps we can chat more tomorrow about better approaches to doing this.

**Comment by sgbaird** [comment]
> Yeah - this is the approach I've taken: one repo for the Python project and a separate (showyourwork-based) repo for the paper, including the former as a dependency. It is a little awkward for development cycle if you're developing them in parallel, so perhaps @rodluger has better advice!

@dfm great to hear the experience of someone else. Thanks!

> Good question! I agree with @dfm that keeping two separate repos is likely the simplest and more elegant approach. Like he said the dev cycle is a little cumbersome because whenever you make a change to your package you need to commit & push to GitHub then change the pinned version in the paper repo's `environment.yml`.
> 
> However, I bet you could save some effort by adding your package as an editable dependency in the paper's `environment.yml`, e.g.:
> 
> ```yaml
> pip:
>    - -e ./relative/path/to/package
> ```
> 
> The catch is that `showyourwork` no longer knows whether anything has changed in your package since the last build (since you're no longer pinning a specific version or commit SHA). So you'd have to manually add your package's files as dependencies in `showyourwork.yml`, which is a bit of a pain (although you could use an [anchor](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) to define all the relevant files up top and alias it in the dependencies of individual scripts to greatly reduce the size of your yaml file).
> 
> You'd also have to edit the `.github/workflows/build.yml` workflow and manually checkout & install your package in the same relative path so things will work on GitHub actions.
> 
> @dfm perhaps we can chat more tomorrow about better approaches to doing this.

I'll keep these suggestions in mind. It sounds either somewhat tedious over and over (releasing new versions) or more upfront work, but only once (editable install). I think I'll lean towards trying to minimize the overlap between the package development and working on the results manuscript (this is aside from a JOSS submission, which lives in the package repo, e.g. [paper.md](https://github.com/sparks-baird/xtal2png/blob/main/reports/paper.md)), and use version pinning* when I need to make (hopefully only a small number of) changes to the package. This also motivates me to expose some of the more general-use plotting functionality in a `utils/plotting.py` file in the package repo and perhaps lean towards exposing these as standalone functions rather than class methods. I think it would also be necessary to return the figure handles (matplotlib or plotly) to make it easy to tweak them for the publication. That way, it's relatively easy to track down the plotting code, it doesn't circumvent the version control, and it doesn't hardcode non-generalized plotting into the package (e.g. a text annotation specific to Figure X).

If you come up with any other ideas or have other thoughts based on your discussion, I'm very interested to hear! @kjappelbaum anything you might want to add?

*maybe using pre-release versions (e.g. `v0.5.1-alpha.1`) that don't run through the full, automated test suite, that I just publish to PyPI locally (+ local tests) to speed things up. Otherwise, 5-10 minutes per small change adds up quickly.

**Comment by rodluger** [comment]
Oh, you could totally use the commit SHA as a unique identifier and install directly from github, e.g.

```
pip:
   - git+https://github.com/user/repo.git@45dfb3641aa4d9828a7c5448d11aa67c7cbd7966
```

which circumvents the need to actually release versions on PyPI. You just have to update that commit every time you want to sync the paper repo with changes in the package repo.

**Comment by sgbaird** [comment]
@rodluger nice! That sounds a lot better than doing the pre-release versioning. I'll plan on that for now.

EDIT: just realized you had mentioned that:
> since you're no longer pinning a specific version or commit SHA
