### ISSUE TITLE
What is the red recycling icon?

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#160]
I noticed a new icon appeared next to my figures - the red recycling icon: 
<img width="37" alt="image" src="https://user-images.githubusercontent.com/41785729/184451421-b1ed3cea-84d2-43b0-bec2-97485538d6a4.png">
What does that mean? When I click on it, it takes me to the same page as the blue dataset icon.

**Comment by rodluger** [comment]
It should point to the Zendo or Zendo Sandbox deposit containing the cached dependency(ies) for that figure. Only shows up for figures with cacheable intermediate steps. Red means the deposit is unpublished/inaccessible to the public; turns blue when you do `showyourwork cache publish`.

Are you sure the link points to the same deposit as the static dataset? If so, that's a bug.

**Comment by rodluger** [comment]
@jfcrenshaw When you get a chance, can you double-check whether the cache icon is pointing to the correct Zenodo Sandbox deposit in your article? Thanks!

**Comment by jfcrenshaw** [comment]
Ah sorry I forgot to respond! They do point to different urls. They just looked like the same deposits because of what I am doing [here](https://github.com/showyourwork/showyourwork/issues/100).

**Comment by rodluger** [comment]
Cool, thanks!
