### ISSUE TITLE
Why is plot_eclipse_overview2.py not being run?

### ISSUE THREAD

**Issue by mkenworthy** [showyourwork/showyourwork#172]
In [mkenworthy/ASASSN-21qj-debris](https://github.com/mkenworthy/ASASSN-21qj-debris) 

The local and remote builds are stopping because:
! Unable to load picture or PDF file `figures/eclipse_overview2.pdf`.

...which is generated by `plot_eclipse_overview2.py` and there's the dependency listed in the `showyourwork.yml`

    src/scripts/plot_eclipse_overview2.py:
        - src/data/obs_ATLAS.ecsv
        - src/data/obs_ASASSN.ecsv
        - src/data/obs_AAVSO.ecsv
...but despite cleaning out the caches and even downloading the repo and starting from scratch, syw is not spotting the dependency and is not running the plotting script. The `ms.tex` figure caption looks identical to other figures, and those scripts are running fine. Why is `plot_eclipse_overview2.py` not being run?

**Comment by rodluger** [comment]
This is due to a duplicate figure label in your manuscript. I created a PR for you here: https://github.com/mkenworthy/ASASSN-21qj-debris/pull/1.

**Comment by mkenworthy** [comment]
Thank you! It didn't occur to me to check for duplicate labels....
