### ISSUE TITLE
DAG.pdf not being generated

### ISSUE THREAD

**Issue by mkenworthy** [showyourwork/showyourwork#176]
I'm seeing if I can get a DAG drawing generated for my syw repo:

https://github.com/mkenworthy/ASASSN-21qj-debris/

I've added `graphviz` to the `environment.yml` and enabled DAG generation in `showyourwork.yml` but no DAG.pdf is generated in the root directory, and there's no error thrown during the make. Not sure what I'm missing.... many thanks!

**Comment by rodluger** [comment]
I introduced the DAG generation option in `0.3.1`, so I think it's just a matter of upgrading! Let me know if that doesn't work.

**Comment by rodluger** [comment]
To be specific: bump the version in your `showyourwork.yml` file.

**Comment by mkenworthy** [comment]
Hmm tried that, now it doesn't compile:


[Tue Aug 30 17:19:54 2022]
Job 1: Setting up the workflow...
Reason: Missing output files: .showyourwork/config.json

Setting up the workflow...
error: terminal input forbidden

Failed to compile manuscript. Perhaps you forgot to `\usepackage{showyourwork}`?
For more information, check out the log file:

**Comment by rodluger** [comment]
Have a look at the `tectonic` log for the build: `.showyourwork/logs/tectonic.log`. If this was on GitHub Actions, just download the `showyourwork-logs` workflow artifact and bring up that file. I suspect it will say you're missing a class file like `aastex631.cls` or `aa.cls`.

In version `0.3.1` we stopped shipping those files with `showyourwork` (for maintainability reasons) so you now have to explicitly include them in your `src/tex` directory.

It's worth reading through the [changelog](https://show-your.work/en/latest/changelog) to see what else is different in the new version.

**Comment by mkenworthy** [comment]
Ah, damn, I didn't realise that - okay, it now builds. Thank you!
