### ISSUE TITLE
Fail the workflow build if the cache is not restored properly

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#188]
@dfm has been running into issues on these lines:

https://github.com/showyourwork/showyourwork/blob/cbbd33da0925371441e9a4a94b1b0bcca105ec5b/showyourwork/cli/commands/cache.py#L63-L68

which fail non-fatally when trying to update the timestamps of files following a cache restore. This results in rules not getting executed on the remote, but the workflow still passes.

I propose we trigger a workflow failure if there's an exception at this point, telling the user to clear the cache by bumping the `article-cache-number` for the next build.

As for the source of the error @dfm was running into, it had something to do with the commit SHA in `last_commit_sha.txt` not being in the repository tree, so the `get_modified_files` function failed with a CalledProcessError. Perhaps the commit was on a fork? Or on a branch that has since been deleted? We should look into this.

**Comment by dfm** [comment]
https://github.com/showyourwork/showyourwork/issues/187

**Comment by rodluger** [comment]
Lol!
