### ISSUE TITLE
Regenerating cache doesn't clear config

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#192]
If (for reasons related to zenodo going funny on me) I delete the zenodo cache using:

```
showyourwork cache delete
```

and then create a new cache with 

```
showyourwork cache create
```

the uploads will fail unless I remove `.showyourwork/config.json`.

This seems like a bug?

**Comment by rodluger** [comment]
Thanks for catching this. I linked a PR (#211) that forces a re-run of the preprocessing step (which generates `.showyourwork/config.json`) whenever `zenodo.yml` changes. Stay tuned.

**Comment by rodluger** [comment]
Hey @arm61 I patched the version on the `main` branch. When you get a chance, can you test it and confirm that the issue is fixed? Thanks!

**Comment by rodluger** [comment]
I believe this is fixed on `main`. Feel free to reopen if needed.

**Comment by arm61** [comment]
Sorry for never getting back on this. I was travelling a lot last month. Looks good to me now though!
