### ISSUE TITLE
Figure Margin Icons overlapping Captions

### ISSUE THREAD

**Issue by bruce-edelman** [showyourwork/showyourwork#202]
Hi, I cannot seem to figure out a way to adjust the location of the figure margin icons and/or captions such that the buttons do not overlap the figure caption in my paper pdf. 

Is this functionality available? Apologies if I missed it somewhere when reading through the documentation but I was not able to find a way to get around it. I am using version 0.3.1 and here is a screenshot of how the icons overlap a figure: 

![image](https://user-images.githubusercontent.com/42656772/192584291-12f35316-ff26-4607-a1e7-6851c8706afe.png)

Thanks!

**Comment by rodluger** [comment]
There's currently no user setting to control this. Which documentclass are you using, and have you tinkered with the page geometry at all, or passed custom options to documentclass?

**Comment by bruce-edelman** [comment]
I have not tinkered with any page geometries, but I am passing options to the aastex63 document class with `\documentclass[twocolumn, linenumber]{aastex63}`

Is that breaking things for me? :sweat_smile:

**Comment by bruce-edelman** [comment]
Okay I was able to fix this by messing with the document class and latex packages, thank you! 

The fix was to switch to AASTex631 and to remove the lineno package that I was using to put the line numbers on: 
```
\usepackage{lineno}
\linenumbers
```

Closing this now :D
