### ISSUE TITLE
MissingInputException when using Overleaf

### ISSUE THREAD

**Issue by TobiBu** [showyourwork/showyourwork#225]
Hi,

I encountered another issue with a static figure and using Overleaf.
I have put a figure into the static folder and I receive the following error message:

`File ms.pdf is present on disk, but there is no valid rule to generate it.
MissingInputException: Missing input files for rule syw__compile:
src/tex/static/279e12_merger_ratio_gas.pdf
MissingInputException: Missing input files for rule syw__arxiv:
src/tex/static/279e12_merger_ratio_gas.pdf`

what am I doing wrong in this case? I have commented out the script command in this case.

**Comment by rodluger** [comment]
Can you push your changes to GitHub? The [tip of your main branch](https://github.com/TobiBu/GSE_merger/tree/eb6a881c88c665bd3c8e186b9c9f20c2671c23dc) does not mention that figure in `ms.tex` -- and the error on GitHub Actions has to do with a missing dataset.

I cloned your repo and added a figure environment for the static figure you mentioned, and it compiled just fine for me.

**Comment by TobiBu** [comment]
Hi,

now everything should be there.

**Comment by rodluger** [comment]
The issue was that static figures are placed in the `src/tex/figures` directory along with the other programmatically-generated figures (not `src/tex/static`).

See https://github.com/TobiBu/GSE_merger/pull/2
