### ISSUE TITLE
Using SyncTeX

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#229]
Hey @rodluger et al,

I was wondering if it's possible to use SyncTeX at all? It seems like there isn't a synctex file generated during the build process. 

In particular I'm using the vscode version - not sure if there's any extra config required given that ms.pdf and ms.tex are in different folders.

Thanks!
Miles

**Comment by rodluger** [comment]
I think you can just add [``--synctex``](https://tectonic-typesetting.github.io/book/latest/v2cli/compile.html) to ``tectonic_args:`` in [``showyourwork.yml``](https://show-your.work/en/latest/config/#tectonic-args), no?

**Comment by MilesCranmer** [comment]
Cool! Didn't know that, thanks. It generates a file `./.showyourwork/compile/ms.synctex.gz` which is great.

Although I just tried using it in vscode (cmd-shift-P, then "Latex workshop: synctex from cursor"), but it doesn't actually connect it. I think maybe VSCode-workshop can't find the synctex file (with default settings), perhaps?

**Comment by MilesCranmer** [comment]
With `cp .showyourwork/compile/ms.synctex.gz ./`, it successfully registers the synctex file and works! So maybe the synctex file needs to be copied to the same location as ms.pdf by default?
