### ISSUE TITLE
`showyourwork.sty` should have fallback definition for \variable{}

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#234]
I was trying to view a generated table on overleaf but it doesn't show up. The fix was to define `\variable` as `\input`. I think this is because right now the style file is as follows:
```tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{showyourwork}[2022/01/12 Open source science articles]

\IfFileExists{./showyourwork.tex}{
    \input{showyourwork.tex}
}{
    \newcommand\GitHubURL{}
    \newcommand\GitHubSHA{}
    \newcommand\GitHubIcon{}
    \newcommand\showyourwork{}
    \newcommand\script[1]{}
    \newcommand\variable[1]{}
}
```
https://github.com/showyourwork/showyourwork-example/blob/main/src/tex/showyourwork.sty

Since `showyourwork.tex` is not used for overleaf builds, I think `\variable` should actually be defined as `\input`, by default, so that generated output files are still loaded in. (just like how `\includegraphics` loads the pre-generated figures).

**Comment by MilesCranmer** [comment]
Btw, the overleaf functionality is AWESOME. Just wanted to mention how much I like it 😃

**Comment by rodluger** [comment]
Good catch. #235 updates the cookiecutter template to make this definition the default. For existing repositories, users should manually make this change to ``src/tex/showyourwork.sty``:

https://github.com/showyourwork/showyourwork/blob/c777d1e12b8a122ef3fa4432e6a10ec59be00116/showyourwork/cookiecutter-showyourwork/%7B%7B%20cookiecutter.repo%20%7D%7D/src/tex/showyourwork.sty#L12
