### ISSUE TITLE
Slow to build environment

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#240]
Currently, my `showyourwork` runs are taking more than 40 minutes to build the conda environment, this seems very long. Is `showyourwork` using `conda` or `mamba`?

**Comment by arm61** [comment]
Is anyone else seeing this behaviour @MilesCranmer @dfm? It is now taking over 1.5 hours on the "Downloading and installing remote packages." step, which is completely breaking the Github action.

**Comment by dfm** [comment]
@arm61 - very strange!! Can you point us to the repo and the action that's stalling out? I'll take a look to see if I can spot anything.

**Comment by arm61** [comment]
It is currently on a private repo. I can add you as a collaborator or share the logs?

**Comment by dfm** [comment]
No problem - sharing the logs and maybe config files should be sufficient, I think! Feel free to email them to me if you prefer.

**Comment by arm61** [comment]
Sent!

**Comment by arm61** [comment]
I had a play about with the `environment.yml` and realised that `r-rsvg` that I was using to convert an svg to pdf was making the condo environment take **ages** to build. I have made work around (where the pdf figure is saved in the static directory instead of the svg. 

Sorry for the wild goose chase.

**Comment by dfm** [comment]
Not at all! I'm glad you got it sorted!!
