### ISSUE TITLE
Correct workflow for Zenodo

### ISSUE THREAD

**Issue by LouisDesdoigts** [showyourwork/showyourwork#245]
Hi showyourwork team, I am currently trying to set up Zenodo integration because of a few intensive calculations but I can't quite figure out how to get the workflow set up correctly!

The basic flow is I have a few scripts that need to be run that generate data that is plotted in some other scripts. I have set up the dependencies and rules as shown in the https://show-your.work/en/latest/zenodo/ page, but I can't seem to get it working. 

I have created a minimal example at on this repo https://github.com/LouisDesdoigts/test_repo/blob/main/showyourwork.yml to simplify debugging. There are two scripts `make_data.py` and `plot_data.py` and I would like to cache the results from `make_data.py` on Zenodo and load the results for plotting in `plot_data.py`. Zenodo is getting valid authentication. 

I have set up the following dependency in `showyourwork.yml`:
```
dependencies:
  src/scripts/plot_data.py:
    - src/data/data.npy
```

and the following rules in the `Snakefile`:
```
rule make_data:
    output:
        "data.npy",
    conda:
        "environment.yml"
    script:
        "src/scripts/make_data.py"

rule plot_data:
    input:
        "data.npy",
    conda:
        "environment.yml"
    script:
        "src/scripts/plot_data.py"
```

When I try and build, I get a `WorkflowError`:

```
WorkflowError:
MissingInputException: Missing input files for rule syw__fig1:
    output: src/tex/figures/sample.pdf
    affected files:
        src/data/data.npy
MissingInputException: Missing input files for rule syw__fig1:
    output: src/tex/figures/sample.pdf
    affected files:
        src/data/data.npy
```

I am likely just missing something simple, so any help is greatly appreciated!
Cheers,
Louis

**Comment by arm61** [comment]
I think that the output in `plot_data` needs to be stated. 

```
rule plot_data:
    input:
        "data.npy"
    output:
        "src/tex/figures/sample.pdf"
    conda:
        "environment.yml"
    script:
        "src/scripts/plot_data.py"
```

**Comment by LouisDesdoigts** [comment]
Beautiful that seems to have done the trick! Cheers.
