### ISSUE TITLE
Discrepancies between local builds and overleaf builds

### ISSUE THREAD

**Issue by LouisDesdoigts** [showyourwork/showyourwork#247]
So I've found that there are font and other minor differences between local and overleaf builds of my paper. I've attached the first page of these two builds as an example. The primary issue is the fonts and size differences, resulting in the paper not matching the journal style. Furthermore it causes the local build to have lots of white space and repositioned figures. I would just use the overleaf build but it doesn't have the git links for showyourwork variables or figures!

I'm not sure how to resolve this discrepancy for final journal submission so any help is greatly appreciated! [Here](https://github.com/LouisDesdoigts/instrumental_calibration/tree/main) is the repo for the project if that helps!

Cheers,
Louis

[page1_local.pdf](https://github.com/showyourwork/showyourwork/files/10243584/page1_local.pdf)
[page1_overleaf.pdf](https://github.com/showyourwork/showyourwork/files/10243580/page1_overleaf.pdf)

**Comment by dfm** [comment]
Looking at the GitHub Actions logs it looks like there might be an issue with the installed fonts. It sounds like SPIE wants you to use Times New Roman, but perhaps that's not installed in a way that TeX can find/use it locally or on GitHub actions. I don't have much experience with this, but perhaps you can try tracking down that issue?

**Comment by dfm** [comment]
Closing as stale, but please feel free to reopen with more info if you have it!
