### ISSUE TITLE
`poetry` support

### ISSUE THREAD

**Issue by jacopok** [showyourwork/showyourwork#289]
Hello,

from reading the documentation it seems like python package management has to be done through conda.
[poetry](https://python-poetry.org/) is an alternative that [may be preferable](https://blogs.sap.com/2022/05/08/why-you-should-use-poetry-instead-of-pip-or-conda-for-python-projects/) (in my opinion it is, at least).

So, it would be nice to be able to use that instead of conda!
I figure introducing this option would be very difficult, since conda is used so widely within your project, but perhaps it might be worth it. I would be willing to work on it.
In any case, since I haven't seen any issue or PR mention poetry, this issue may serve as a place to point to where the developers' stance on this issue is written down explicitly.

**Comment by arm61** [comment]
I think that the reason for using conda is to because there are non-python dependencies (specifically tectonic) but I am sure @dfm knows better than I.

**Comment by dfm** [comment]
Thanks @jacopok! This design constraint actually comes from [snakemake](https://github.com/snakemake/snakemake) which provides the back end. conda/mamba is tightly integrated into snakemake for better or worse. I won't weigh in too many opinions on this, but I'd say that the reproducible workflows that snakemake (and showyourwork) are targeting are probably better served by conda than poetry, with different constraints than those discussed for production environments. I'm not sure if anyone has thought about using poetry with snakemake, but it might be feasible to hack it together! Either way I'd say that it's out of scope for showyourwork core, but I'd love to see an example if you put something together!

**Comment by jacopok** [comment]
Great, thanks! Then I'll close this as out of scope, and let you know if I can figure something out.
