### ISSUE TITLE
Monochrome margin icons

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#290]
For some the coloured margin icons are a bit garish. It would be nice to have an option in the `yml` to customise these colours (or specifically make them black).

The colours seem to be hardcoded here: https://github.com/showyourwork/showyourwork/blob/697779a1c7f787fe9e1a3ff15fcdd86649ddf845/showyourwork/workflow/resources/styles/build.tex#L58
Tips on how the stuff defined in the `showyourwork.yml` gets into there?

**Comment by dfm** [comment]
Good idea. That file isn't dynamically generated, but there's a separate file called `showyourwork-metadata.tex` that gets generated by [`workflow/scripts/compile_setup.py`](https://github.com/showyourwork/showyourwork/blob/697779a1c7f787fe9e1a3ff15fcdd86649ddf845/showyourwork/workflow/scripts/compile_setup.py). 

You could move the existing definitions to the `else` of this conditional:

https://github.com/showyourwork/showyourwork/blob/697779a1c7f787fe9e1a3ff15fcdd86649ddf845/showyourwork/workflow/resources/styles/build.tex#L40-L48

And then have `compile_setup.py` collect things from the config. Happy to chat more about specifics!
