### ISSUE TITLE
Demonstrate how to activate conda environment for debugging scripts

### ISSUE THREAD

**Issue by dfm** [showyourwork/showyourwork#299]
The conda environments all live within `.snakemake` so we could use that, but a better approach might be to just document how to create/update an environment from the `environment.yaml` file to use that.

**Comment by rwegener2** [comment]
Hi @dfm! I'm working on this and trying to decide where the best place to put this is in the docs. Do you have a bit more context about what prompted this request to help decide where to put it? I thought a user shouldn't actually have to use conda manually. Alternately if you know where you think this should go that works, too!
