### ISSUE TITLE
Document the use of `mamba` for solving environments

### ISSUE THREAD

**Issue by HealthyPear** [showyourwork/showyourwork#330]
I see that this already popped out in issues like #240, but I felt the need to ask/suggest explicitly.

Ae already using mamba to create the conda envs?  If not I'd suggest to do it as it is sensibly faster.
You could use the mambaforge distribution.

**Comment by dfm** [comment]
Since `v0.4.2` (this PR, specifically: https://github.com/showyourwork/showyourwork/pull/268) `mamba` is supported as follows:

```bash
showyourwork build --conda-frontend=mamba
```

but that's not really documented anywhere so it would be great to add that!
