### ISSUE TITLE
Integrating Overleaf error when setup

### ISSUE THREAD

**Issue by iphysresearch** [showyourwork/showyourwork#337]
I followed the setup tutorial with command `showyourwork setup iphysresearch/DLGW_review --overleaf=64254ea499a2ff8e814a607d --cache` but encounter the error when integrating Overleaf as below:
```bash
Overleaf repository not empty! Refusing to rewrite files on remote.
```
<img width="558" alt="image" src="https://user-images.githubusercontent.com/14322948/228786779-cd0c10df-46f2-4274-93e0-11efc433da0b.png">

My target project shows here:
![image](https://user-images.githubusercontent.com/14322948/228787882-74a1ee06-6657-4621-b273-e14b25799b78.png)

The version of showyourwork is `0.4.2`.

**Comment by mkenworthy** [comment]
Hi, the problem is detailed in https://github.com/showyourwork/showyourwork/issues/322  :

but TL;DR

change 
`\usepackage{graphicx}`

to
`\usepackage[utf8]{inputenc}`

...in the new Overleaf and your showyourwork command should now work!

**Comment by iphysresearch** [comment]
> Hi, the problem is detailed in #322 :
> 
> but TL;DR
> 
> change `\usepackage{graphicx}`
> 
> to `\usepackage[utf8]{inputenc}`
> 
> ...in the new Overleaf and your showyourwork command should now work!

Awesome! Perfectly resolved!

<img width="516" alt="image" src="https://user-images.githubusercontent.com/14322948/228855548-fea17ead-e724-4d8a-943a-bfcc90ced78d.png">
