### ISSUE TITLE
showyourwork always re-runs everything

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#341]
I'm coming back to a paper (https://github.com/jfcrenshaw/pzflow-paper) that I need to do revisions on, and have found that suddenly showyourwork wants to re-run things all the time, including creating the conda environment.

If I run `showyourwork build` it starts running everything, and if I let that finish, and then immediately run `showyourwork build` again, it does it again!

Since I last ran this repo, the code definitely hasn't changed, and to the best of my knowledge, neither has the conda environment I used for development. 

I realize this is a vague problem with a large repo -- I'm wondering if you have any advice how to go about figuring out *why* showyourwork is behaving this way? I'm not sure where to look. For example, I've tried doing `showyourwork build --verbose`, but that doesn't tell me why it wants to re-create the conda environment.

**Comment by dfm** [comment]
I'm not sure what's up with this, but one thing you might want to start with is deleting the `.showyourwork` and `.snakemake` directories in the root of the repository to see if that fixes things. Otherwise, what version of showyourwork are you running?

**Comment by jfcrenshaw** [comment]
I ended up removing everything, cloning a clean repo, and starting from scratch, and it seems that this issue has resolved itself... ¯\_(ツ)_/¯ 

I'll close this now -- sorry for the noise!
