### ISSUE TITLE
Update overview figure to include other language scripts

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#343]
The overview figure has the "Python" logo next to the "pipeline scripts" and "figure scripts":

![image](https://user-images.githubusercontent.com/7593028/232333761-80a32b69-107b-42a5-863d-ec5e1ce8bb0b.png)

I think this is misleading for people checking out the project because they may immediately think their {Julia/R/Rust} scripts can not be used in their SYW project. (In fact, the reason I am aware of this issue is because a Julia person thought they couldn't use SYW). However, Snakemake has native support for all four: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#external-scripts, and is also able to execute arbitrary shell commands.

@rodluger would you happen to have the source file for this overview figure? I'd propose that we either tweak it to have other language logos, or just remove any particular language's logo altogether. What do you think @dfm?

---

side note: it could be useful to include `paths.jl`, `paths.rs`, `paths.R` in the cookie-cutter template. Maybe we could have a "languages to support" option when creating the template repository that would download the needed scripts in each case, and update the `showyourwork.yml` file to map the filetypes.

**Comment by dfm** [comment]
+1 All good with me!
