### ISSUE TITLE
tarball includes `ms.bib`

### ISSUE THREAD

**Issue by MilesCranmer** [showyourwork/showyourwork#359]
The arXiv tarball should remove `ms.bib` and replace it with `ms.bbl`. However it seems like both are in the tarballs.

**Comment by dfm** [comment]
This should be as simple as adding `ms.bib` to `exclude` in [`showyourwork/workflow/scripts/arxiv.py`](https://github.com/showyourwork/showyourwork/blob/ae0150e95d67a715d204e3bf7477087212a2a975/showyourwork/workflow/scripts/arxiv.py)!

**Comment by MilesCranmer** [comment]
How do we know the name of the `.bib` file? Or should we just recursively filter all `.bib` in the directory?

**Comment by dfm** [comment]
Good point! I think it's probably fine to exclude all `*.bib` files, right?

**Comment by MilesCranmer** [comment]
Yep. IIRC arXiv doesn't even let you build with them
