### ISSUE TITLE
Quickstart tutorial not working

### ISSUE THREAD

**Issue by nikosarcevic** [showyourwork/showyourwork#431]
When I click on the [quickstart tutorial](https://show-your.work/en/latest/quickstart), it gives me a 404 page.
Not sure if you are aware of it (if it is being developed), but thought it would be good to let you know.

Great work, otherwise, kudos!

**Comment by dfm** [comment]
Thanks! I've fixed this over in #432, and the webpage should be updated shortly.

**Comment by nikosarcevic** [comment]
> Thanks! I've fixed this over in #432, and the webpage should be updated shortly.

thank you on behalf of me and others on Twitter.
cheers!
