### ISSUE TITLE
Permission denied to github-actions[bot].

### ISSUE THREAD

**Issue by SiyiZhao** [showyourwork/showyourwork#457]
It works on my laptop, but after the push to GitHub, it shows: 
<img width="917" alt="image" src="https://github.com/showyourwork/showyourwork/assets/52352980/544df840-7455-4ed1-90cb-8c9fb2190235">

**Comment by HealthyPear** [comment]
This error is explained in the FAQ of the project:
https://show-your.work/en/latest/faqs/#permissions-errors-in-github-actions

Can you try to do what is explained there and confirm if it works for you?

**Comment by SiyiZhao** [comment]
It works, thanks a lot.
