### ISSUE TITLE
syw frozen on `Generating XML tree...`

### ISSUE THREAD

**Issue by mkenworthy** [showyourwork/showyourwork#461]
I started a new showyourwork, and got the first version with ApJ format working.

I swapped in a new ms.tex file in A&A style, and now the syw build fails on `Preprocess: Generating XML tree...`

I've tried adding a latency-wait to 500 seconds, but no joy. It's frozen.

> `sw build --latency-wait 500                                                                                  
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Fetching Overleaf repo...
Pulling changes from Overleaf: src/tex/ms.tex src/tex/bib.bib
No Overleaf changes to commit to the repo.
Preprocess: Generating XML tree...
MissingOutputException in rule syw__preprocess_xml in line 40 of /Users/kenworthy/anaconda3/envs/syw3/lib/python3.10/site-packages/showyourwork/workflow/rules/preprocess.smk:
Job Missing files after 50 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/Users/kenworthy/BetaPicPLATO_scrap/.showyourwork/preprocess/showyourwork.xml completed successfully, but some output files are missing. 2
Exiting because a job execution failed. Look above for error message`

**Comment by HealthyPear** [comment]
Can you share a minimal reproducible example in a zipped file?

**Comment by mkenworthy** [comment]
Working on making a minimal version, and I spotted my mistake - I had commented out the `\include{showyourwork}` in my tex file. Putting it back in the correct place solved the problem.
