### ISSUE TITLE
remote build error: write access not granted

### ISSUE THREAD

**Issue by outs1der** [showyourwork/showyourwork#493]
New user to showyourwork with possibly a trivial issue, but it's mystifying to me

Remote build fails consistently with a "write access not granted" error at the stage of uploading logs (or something). Relevant section below (copied from the log section of the "Build the article PDF" action on GitHub).

> Uploading logs
  Starting artifact upload
  For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
  Artifact name is valid!
  Container for artifact "showyourwork-logs" successfully created. Starting upload of file(s)
  Total size of all the files uploaded is 2033456 bytes
  File upload process has finished. Finalizing the artifact upload
  Artifact has been finalized. All files have been successfully uploaded!
>  
>  The raw size of all the files that were specified for upload is 2961024 bytes
  The size of all the files that were uploaded is 2033456 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage
>  
>  Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 
>  
> Error: exec: remote: Write access to repository not granted.
>
> fatal: unable to access 'https://github.com/outs1der/beans3/': The requested URL returned error: 403

Got everything set up locally and also with overleaf integration. Had a few hiccups on the setup, because I initially used an OVERLEAF_USERNAME and OVERLEAF_PASSWORD instead of a token, but the overleaf upload seems to be working

Set up the repo as private initially, was wondering if that might be an issue.

**Comment by HealthyPear** [comment]
This should be your issue:
https://show-your.work/en/latest/faqs/#permissions-errors-in-github-actions

Please, let me know if this fixes your problem!

**Comment by outs1der** [comment]
Yep, that fixed it – thanks! (and sorry I missed this in the FAQ, I did look!)
