### ISSUE TITLE
Automatic citation of software

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#50]
We should think about how to support this (automatically citing software used in the workflow by including it in, e.g., the ``Software`` section of a AAS journal article). This is something I believe [Maneage](https://maneage.org/index.html) does. 

It would also be cool to take this a step further and try to find the BibTeX entry corresponding to a given package. There probably isn't an automated, full-proof way of doing this, but perhaps we could try to parse the README files on PyPI and look for BibTeX entries? @dfm @adrn any ideas here?

**Comment by adrn** [comment]
Great idea! We should chat - we may be able to re-purpose some code from https://github.com/adrn/makecite

**Comment by rodluger** [comment]
Oh cool, I didn't know about ``makecite``. Yes, let's chat! In the meantime I've thrown together some code here: https://github.com/rodluger/citeyoursoftware

But if it makes more sense, I'm happy to merge this stuff into ``makecite`` once we get it working.

**Comment by rodluger** [comment]
Punting on this for now. But I'll keep thinking about it...
