### ISSUE TITLE
add support for other README.org and/or other  formats?

### ISSUE THREAD

**Issue by mathren** [showyourwork/showyourwork#87]
I often use emacs org-mode for READMEs, and I can successfully `make` locally (and have the badges to make it look nice, etc.). However, when github actions does the `make`, after producing the pdf, the build PDF step fails with:

```
Uploading output
Total size of all the files uploaded is 8998316 bytes
Finished uploading artifact showyourwork-output. Reported size is 8998316 bytes. There were 0 items that failed to upload
Error: grep: no such file or directory: README.md
```

 I think this error may come from line 31 in `index.js` which may be modified with a try/catch to explot a few common README extensions (.md, .org, .rst, etc.) maybe, but I'm not sure this is the only place where this would be needed.

**Comment by rodluger** [comment]
Sorry it took me so long to address this. I rewrote the entire package and will release the new version in the next ~week. Showyourwork is now a python package, so this hack to infer the version number is no longer needed.

**Comment by rodluger** [comment]
Closing this for now. Feel free to reopen if you run into similar issues with v1. It's currently on the dev branch if you want to play around with it (docs being written as fast as I can!)
