### ISSUE TITLE
Provide generic instructions about how to build manuscript

### ISSUE THREAD

**Issue by adrn** [showyourwork/showyourwork#93]
When working on the latest [Astropy paper](https://github.com/astropy/astropy-v5.0-paper) (which uses showyourwork), I forgot to clearly explain how to build the PDF of the manuscript, so many people naively tried to run `pdflatex` directly (which failed), or ran `make` and were confused about what it was doing. I then added some [text to the README](https://github.com/astropy/astropy-v5.0-paper#building-the-paper-locally) to explain, but it would be great to provide some boilerplate explanation and instructions in the example/template repo, or maybe in the `showyourwork` docs?

**Comment by rodluger** [comment]
Good idea. I've added instructions to the landing page on the docs and to the ``quickstart`` page.
